export const colors = [
  { name: 'black / off', value: 0 },
  { name: 'dark grey', value: 1 },
  { name: 'grey', value: 2 },
  { name: 'white', value: 3 },
  { name: 'white-red (rose?)', value: 4 },
  { name: 'red [bright]', value: 5 },
  { name: 'red', value: 6 },
  { name: 'red [dim]', value: 7 },
  { name: 'red-amber', value: 8 },
  { name: 'amber [bright]', value: 9 },
  { name: 'amber', value: 10 },
  { name: 'amber [dim]', value: 11 },
  { name: 'amber-yellow', value: 12 },
  { name: 'yellow [bright]', value: 13 },
  { name: 'yellow', value: 14 },
  { name: 'yellow [dim]', value: 15 },
  { name: 'yellow-lime', value: 16 },
  { name: 'lime [bright]', value: 17 },
  { name: 'lime', value: 18 },
  { name: 'lime [dim]', value: 19 },
  { name: 'lime-greenish', value: 20 }, // Corrected typo "greeinish" to "greenish"
  { name: 'green [bright]', value: 21 },
  { name: 'green', value: 22 },
  { name: 'green [dim]', value: 23 },
  { name: 'green-spring', value: 24 },
  { name: 'spring [bright]', value: 25 },
  { name: 'spring', value: 26 },
  { name: 'spring [dim]', value: 27 },
  { name: 'spring-turquoise', value: 28 },
  { name: 'turquoise [bright]', value: 29 },
  { name: 'turquoise', value: 30 },
  { name: 'turquoise [dim]', value: 31 },
  { name: 'turquoise-cyan', value: 32 },
  { name: 'cyan [bright]', value: 33 },
  { name: 'cyan', value: 34 },
  { name: 'cyan [dim]', value: 35 },
  { name: 'cyan-sky', value: 36 },
  { name: 'sky [bright]', value: 37 },
  { name: 'sky', value: 38 },
  { name: 'sky [dim]', value: 39 },
  { name: 'sky-ocean', value: 40 },
  { name: 'ocean [bright]', value: 41 },
  { name: 'ocean', value: 42 },
  { name: 'ocean [dim]', value: 43 },
  { name: 'ocean-blue', value: 44 },
  { name: 'blue [bright]', value: 45 },
  { name: 'blue', value: 46 },
  { name: 'blue [dim]', value: 47 },
  { name: 'blue-orchid', value: 48 },
  { name: 'orchid [bright]', value: 49 },
  { name: 'orchid', value: 50 },
  { name: 'orchid [dim]', value: 51 },
  { name: 'orchid-magenta', value: 52 },
  { name: 'magenta [bright]', value: 53 },
  { name: 'magenta', value: 54 },
  { name: 'magenta [dim]', value: 55 },
  { name: 'magenta-pink', value: 56 },
  { name: 'pink [bright]', value: 57 },
  { name: 'pink', value: 58 },
  { name: 'pink [dim]', value: 59 },
  { name: 'bright orange', value: 60 }
];
